spring.application.name=inkluziv
server.port=8081

spring.data.mongodb.uri=mongodb+srv://victor:Kingvic@inkluziv.vvlocrl.mongodb.net/?retryWrites=true&w=majority&appName=inkluziv
spring.data.mongodb.database=inkluziv

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oladimejivictor611@gmail.com
spring.mail.password=ypbl kohs jouh phxa
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

voice.ml.service.url=https://voice-embedding-api.onrender.com

RESET_JWT_SECRET=Lro7KxAF6IvxTbQqynMFdzqHCL1m55CvaZ/V2M2ulawETobWLXXHZp3P5nMC+wMf401
RESET_JWT_EXPIRATION=120000

CLOUDINARY_CLOUD_NAME=dne74lnhk
CLOUDINARY_API_KEY=919725957683897
CLOUDINARY_API_SECRET=ikFY_3mXaiwBUeFMMZoD-k6Yljo

spring.security.oauth2.client.registration.google.client-id=31415212217-606mri9r2adon27kj4cse957e5natmnj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8000/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,email,profile
